[package]
name = "kvstore"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
rocksdb = "0.22"
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["sync"] }