[workspace]
resolver = "2"
members = [
    "full-node",
    "sdk/block-commitment",
    "sdk/context",
    "sdk/json-rpc",
    "sdk/kvstore",
    "sdk/liveness-radius",
    "sdk/signature",
    "sdk/validation-eigenlayer",
    "sequencer",
]

[workspace.dependencies]
alloy = { version = "0.2", default-features = false }
bincode = "1.3"
futures = "0.3"
pin-project = "1.1"
rand = "0.8"
serde = { version = "1.0.197", default-features = false }
serde_json = { version = "1.0", default-features = false }
tokio = { version = "1.0", default-features = false }
