[package]
name = "liveness-evm"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true, features = ["full", "reqwest", "signer-local"] }
futures = { workspace = true }
pin-project = { workspace = true }