[package]
name = "signature"
version = "0.1.0"
edition = "2021"

[dependencies]
const-hex = "1.12"
ed25519-dalek = "2.1"
k256 = { version = "0.13", features = ["ecdsa"] }
serde = { workspace = true, features = ["derive"] }

alloy = { workspace = true, features = ["signer-local"] }