[package]
name = "validation-eigenlayer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true, features = ["full", "reqwest", "signer-local"] }
chrono = "0.4"
futures = { workspace = true }
pin-project = { workspace = true }
rand = { workspace = true }